export const handleError = (error: Error) => {
  console.log('Catch error --->', error);
};
